std = "lua51"
max_line_length = false
codes = true
exclude_files = {
	"**/.libraries",
    "**/libs"
}

ignore = {
    "212/self",
}
globals = {

	"bit",
	"C_Bank",
	"C_Container",
	"C_EquipmentSet",
	"C_Item",
	"C_NewItems",
	"C_Timer",
	"C_TooltipInfo",
	"C_TransmogCollection",
	"ClearCursor",
	"ContinuableContainer",
	"CreateFrame",
	"debugstack",
	"Enum",
	"floor",
	"format",
	"GameMenuFrame",
	"GetCursorInfo",
	"GetDetailedItemLevelInfo",
	"GetInventoryItemLink",
	"GetInventoryItemQuality",
	"GetItemInfo",
	"GetTalentTabInfo",
	"hooksecurefunc",
	"InCombatLockdown",
	"INVSLOT_FIRST_EQUIPPED",
	"INVSLOT_LAST_EQUIPPED",
	"Item",
	"ItemLocation",
	"LibStub",
	"EquipmentManager_UnpackLocation",
	"EquipmentManager_GetLocationData",
	"NUM_BANKGENERIC_SLOTS",
	"gsub",
	"sort",
	"strfind",
	"string.join",
	"string.split",
	"strjoin",
	"strsplittable",
	"strlen",
	"strlower",
	"strmatch",
	"strrep",
	"strsplit",
	"strsub",
	"strtrim",
	"strupper",
	"table.wipe",
	"tan",
	"time",
	"tinsert",
	"tremove",
	"tContains",
	"WorldFrame",
	"wipe",
}
