local addonName = ... ---@type string

if GetLocale() ~= 'enUS' then return end

---@class BetterBags: AceAddon
local addon = LibStub('AceAddon-3.0'):GetAddon(addonName)

---@class Localization: AceModule
local L = addon:GetModule('Localization')

L:S("Alphabetically", true)
L:S("Alphabetically, then Quality", true)
L:S("Ammo Pouch", true)
L:S("Are you sure you want to delete this category?", true)
L:S("Backpack", true)
L:S("Bags", true)
L:S("Bank", true)
L:S("BetterBags", true)
L:S("Cannot change bags in combat.", true)
L:S("Cannot toggle bag slots in combat.", true)
L:S("Categories you create can be enabled and disabled just like the default categories in the configuration menu option for the bag (Backpack or Bank) on the left. Once you have created a category, you can configure it by selecting it on the menu on the left.", true)
L:S("Categories", true)
L:S("Clean Up Warbank", true)
L:S("Click to clean up your Warbanks and resort items into correct tabs.", true)
L:S("Click to deposit all reagents into your reagent bank.", true)
L:S("Click to open the options screen.", true)
L:S("Click to toggle the display of the Blizzard bag button.", true)
L:S("Click to toggle the display of the bag slots.", true)
L:S("Click to toggle the display of the category configuration side panel.", true)
L:S("Click to toggle the display of the currencies side panel.", true)
L:S("Click to toggle the display of the theme configuration side panel.", true)
L:S("Close Menu", true)
L:S("Color the item level text based on the item's quality.", true)
L:S("Color", true)
L:S("Columns", true)
L:S("Configure Categories", true)
L:S("Create Category", true)
L:S("Currencies", true)
L:S("Custom Categories", true)
L:S("Custom categories allow you to create your own categories for items. Type the name of the category you want to create in the box below and press enter to create an empty category.", true)
L:S("Delete Category", true)
L:S("Deposit All Reagents", true)
L:S("Deposit Warbank Items", true)
L:S("Display", true)
L:S("Don't Merge Partial", true)
L:S("Don't Merge Transmog", true)
L:S("Don't merge stacks of items that aren't full stacks.", true)
L:S("Don't merge stacks of items that have different transmogs on them.", true)
L:S("Drag an item here from your inventory, bank, or another source to add it to this category.", true)
L:S("Drag an item here to add it to this category.", true)
L:S("Drop %s here to create a new category for it.", true)
L:S("Empty Bag Slot", true)
L:S("Empty Reagent Bag Slot", true)
L:S("Empty Slot", true)
L:S("Enable In-Bag Search", true)
L:S("Enabled", true)
L:S("Enchanting Bag", true)
L:S("Engineering Bag", true)
L:S("Engineering", true)
L:S("Equipment Location", true)
L:S("Equipped Bags", true)
L:S("Everything", true)
L:S("Expansion", true)
L:S("Flash new items in stacks", true)
L:S("Free Slots", true)
L:S("Free Space", true)
L:S("Gear Set", true)
L:S("Gem Bag", true)
L:S("General", true)
L:S("Help", true)
L:S("Herb Bag", true)
L:S("Herbalism", true)
L:S("Hide Category", true)
L:S("How do I delete an item from a custom category?", true)
L:S("How do I search for items?", true)
L:S("If enabled, a search bar will appear at the top of your bags.", true)
L:S("If enabled, all new items added to the bag will be marked as recent, i.e. bank -> backpack.", true)
L:S("If enabled, stacks that receive new items will flash to indicate the addition of a new item.", true)
L:S("If you delete a custom category that was created by another addon/plugin, it will reappear the next time you log in/reload. To permanently delete a custom category created by a plugin/another addon, you must disable the addon creating the category and then delete the category in the UI.", true)
L:S("Incoming items are recent", true)
L:S("Inscription Bag", true)
L:S("Item Level", true)
L:S("Item Sorting", true)
L:S("Items Per Row", true)
L:S("Items can only be in one category at a time. If you have a category that is missing items, it is likely that the items in that category are already in another category.", true)
L:S("Items", true)
L:S("Junk", true)
L:S("Keyring", true)
L:S("Leatherworking Bag", true)
L:S("Leatherworking", true)
L:S("Left Click", true)
L:S("Merge Stacks", true)
L:S("Merge Unstackable", true)
L:S("Merge stacks of the same item into a single stack, i.e. 20x [Linen Cloth] + 20x [Linen Cloth, 40x [Linen Cloth] in one stack.", true)
L:S("Merge stacks of the same item into a single stack.", true)
L:S("Merge unstackable items of the same kind into a single stack, such as armors, bags, etc.", true)
L:S("Mining Bag", true)
L:S("Mining", true)
L:S("New Category Name", true)
L:S("New Item Duration", true)
L:S("New Items", true)
L:S("No custom categories have been created yet.", true)
L:S("Opacity", true)
L:S("Open Menu", true)
L:S("Open Options Screen", true)
L:S("Plugin configuration options can be accessed on the left by expanding the 'Plugins' menu option.", true)
L:S("Plugins", true)
L:S("Quality, then Alphabetically", true)
L:S("Quiver", true)
L:S("Reagent Bank", true)
L:S("Recent Items", true)
L:S("Remove", true)
L:S("Right Click", true)
L:S("Scale", true)
L:S("Search Bags", true)
L:S("Search", true)
L:S("Section Sorting", true)
L:S("Select how items should be sorted.", true)
L:S("Select how sections should be sorted.", true)
L:S("Select which categories to show in this bag. If an option is checked, items that belong to the checked category will be put into a section for that category.", true)
L:S("Select which custom categories to show in this bag. If an option is checked, items that belong to the checked category will be put into a section for that category.", true)
L:S("Set the number of columns sections will fit into.", true)
L:S("Set the number of items per row in this bag.", true)
L:S("Set the opacity of this bag.", true)
L:S("Set the scale of this bag.", true)
L:S("Shift Left Click", true)
L:S("Show All Free Space Slots", true)
L:S("Show Bag Button", true)
L:S("Show Bags", true)
L:S("Show Blizzard Bag Button", true)
L:S("Show Currencies", true)
L:S("Show Full Section Names", true)
L:S("Show all free space slots in the bag window.", true)
L:S("Show or hide the default Blizzard bag button.", true)
L:S("Show the full section in the bag window without truncating it with '...'", true)
L:S("Show the item level of items in this bag.", true)
L:S("Size Ascending", true)
L:S("Size Descending", true)
L:S("Sort Bags", true)
L:S("Soul Bag", true)
L:S("Stacking", true)
L:S("Subtype", true)
L:S("Tailoring", true)
L:S("The time, in minutes, to consider an item a new item.", true)
L:S("Theme Configuration", true)
L:S("Themes", true)
L:S("Trade Skill", true)
L:S("Type", true)
L:S("Unknown", true)
L:S("Unmerge all items when visiting a vendor.", true)
L:S("Unmerge at Shop", true)
L:S("Welcome to Better Bags! Please select a help item from the left menu for FAQ's and other information.", true)
L:S("What would you like to name the new category for %s?", true)
L:S("When viewing a custom category configuration, you can right click on an item to open it's menu and select 'delete' to delete it from the category.", true)
L:S("Why are some of my items not showing up in my custom categories?", true)
L:S("Why does a custom category reappear after I delete it?", true)

-- Plugin: BetterSort
L:S("If enbaled, Blizzard \"New Item Tag\" will be ignored. This makes new items strictly rely on \"New Item Duration\" setting.", true)
L:S("Ignore New Item Tag", true)
L:S("Item Level Descending", true)
L:S("Sort by Item Level", true)
L:S("Sort Descendingly.", true)
L:S("Sort Items by Item Level.", true)
