-- intervaltree_spec.lua -- Unit tests for util/trees/ (Trees + IntervalTree)

local addon = LibStub("AceAddon-3.0"):GetAddon("BetterBags")
-- trees.lua must load first (creates the Trees module), then intervaltree.lua (adds methods)
LoadBetterBagsModule("util/trees/trees.lua")
LoadBetterBagsModule("util/trees/intervaltree.lua")
local Trees = addon:GetModule("Trees")

-- Helper: extract values from a list of IntervalTreeNodes
local function nodeValues(nodes)
  local values = {}
  for _, node in ipairs(nodes) do
    table.insert(values, node.value)
  end
  table.sort(values)
  return values
end

-- Helper: extract slotkeys from a list of nodes (flattened)
local function nodeSlotKeys(nodes)
  local keys = {}
  for _, node in ipairs(nodes) do
    for k in pairs(node.data or {}) do
      keys[k] = true
    end
  end
  return keys
end

describe("IntervalTree", function()

  local tree

  before_each(function()
    tree = Trees.NewIntervalTree()
  end)

  -- ─── Insert ─────────────────────────────────────────────────────────────────

  describe("Insert", function()

    it("inserts a single value", function()
      tree:Insert(10, {a = true})
      local node = tree:ExactMatch(10)
      assert.is_not_nil(node)
      assert.are.equal(10, node.value)
      assert.same({a = true}, node.data)
    end)

    it("inserts multiple values into a BST structure", function()
      tree:Insert(10, {a = true})
      tree:Insert(5, {b = true})
      tree:Insert(15, {c = true})
      assert.is_not_nil(tree:ExactMatch(10))
      assert.is_not_nil(tree:ExactMatch(5))
      assert.is_not_nil(tree:ExactMatch(15))
    end)

    it("merges data when inserting a duplicate value", function()
      tree:Insert(10, {a = true})
      tree:Insert(10, {b = true})
      local node = tree:ExactMatch(10)
      assert.same({a = true, b = true}, node.data)
    end)

    it("overwrites a data key on duplicate insert", function()
      tree:Insert(10, {a = "first"})
      tree:Insert(10, {a = "second"})
      local node = tree:ExactMatch(10)
      assert.are.equal("second", node.data.a)
    end)
  end)

  -- ─── Min/max maintenance on insert ──────────────────────────────────────────

  describe("min/max on insert", function()

    it("root min/max tracks own value when alone", function()
      tree:Insert(10, {a = true})
      local root = tree:ExactMatch(10)
      assert.are.equal(10, root.min)
      assert.are.equal(10, root.max)
    end)

    it("root min/max spans left and right children", function()
      tree:Insert(10, {a = true})
      tree:Insert(5, {b = true})
      tree:Insert(15, {c = true})
      local root = tree:ExactMatch(10)
      assert.are.equal(5, root.min)
      assert.are.equal(15, root.max)
    end)

    it("root min tracks deepest left subtree", function()
      tree:Insert(10, {a = true})
      tree:Insert(5, {b = true})
      tree:Insert(3, {c = true})
      tree:Insert(1, {d = true})
      local root = tree:ExactMatch(10)
      assert.are.equal(1, root.min)
    end)

    it("root max tracks deepest right subtree", function()
      tree:Insert(10, {a = true})
      tree:Insert(15, {b = true})
      tree:Insert(20, {c = true})
      tree:Insert(25, {d = true})
      local root = tree:ExactMatch(10)
      assert.are.equal(25, root.max)
    end)

    it("root min/max tracks a full balanced tree", function()
      tree:Insert(50, {a = true})
      tree:Insert(30, {b = true})
      tree:Insert(70, {c = true})
      tree:Insert(20, {d = true})
      tree:Insert(40, {e = true})
      tree:Insert(60, {f = true})
      tree:Insert(80, {g = true})
      local root = tree:ExactMatch(50)
      assert.are.equal(20, root.min)
      assert.are.equal(80, root.max)
    end)

    it("interior node min/max tracks its own subtree", function()
      tree:Insert(50, {a = true})
      tree:Insert(30, {b = true})
      tree:Insert(70, {c = true})
      tree:Insert(20, {d = true})
      tree:Insert(40, {e = true})
      local left = tree:ExactMatch(30)
      assert.are.equal(20, left.min)
      assert.are.equal(40, left.max)
    end)

    it("min/max unchanged by duplicate insert", function()
      tree:Insert(10, {a = true})
      tree:Insert(5, {b = true})
      tree:Insert(10, {c = true})
      local root = tree:ExactMatch(10)
      assert.are.equal(5, root.min)
      assert.are.equal(10, root.max)
    end)

    it("min/max correct for right-heavy tree", function()
      tree:Insert(10, {a = true})
      tree:Insert(20, {b = true})
      tree:Insert(15, {c = true})
      tree:Insert(25, {d = true})
      local root = tree:ExactMatch(10)
      assert.are.equal(10, root.min)
      assert.are.equal(25, root.max)
      local right = tree:ExactMatch(20)
      assert.are.equal(15, right.min)
      assert.are.equal(25, right.max)
    end)

    it("min/max correct for left-heavy tree", function()
      tree:Insert(20, {a = true})
      tree:Insert(10, {b = true})
      tree:Insert(15, {c = true})
      tree:Insert(5, {d = true})
      local root = tree:ExactMatch(20)
      assert.are.equal(5, root.min)
      assert.are.equal(20, root.max)
      local left = tree:ExactMatch(10)
      assert.are.equal(5, left.min)
      assert.are.equal(15, left.max)
    end)
  end)

  -- ─── Min/max maintenance on remove ──────────────────────────────────────────

  describe("min/max on remove", function()

    it("removing a leaf updates parent min/max", function()
      tree:Insert(10, {a = true})
      tree:Insert(5, {b = true})
      tree:Insert(15, {c = true})
      tree:RemoveData(5, "b")
      local root = tree:ExactMatch(10)
      assert.are.equal(10, root.min)
      assert.are.equal(15, root.max)
    end)

    it("removing the min leaf correctly updates ancestors", function()
      tree:Insert(50, {a = true})
      tree:Insert(30, {b = true})
      tree:Insert(70, {c = true})
      tree:Insert(20, {d = true})
      tree:Insert(40, {e = true})
      tree:RemoveData(20, "d")
      local root = tree:ExactMatch(50)
      assert.are.equal(30, root.min)
      assert.are.equal(70, root.max)
      local left = tree:ExactMatch(30)
      assert.are.equal(30, left.min)
      assert.are.equal(40, left.max)
    end)

    it("removing the max leaf correctly updates ancestors", function()
      tree:Insert(50, {a = true})
      tree:Insert(30, {b = true})
      tree:Insert(70, {c = true})
      tree:Insert(60, {d = true})
      tree:Insert(80, {e = true})
      tree:RemoveData(80, "e")
      local root = tree:ExactMatch(50)
      assert.are.equal(30, root.min)
      assert.are.equal(70, root.max)
    end)

    it("removing root when it has children (inorder predecessor replacement)", function()
      tree:Insert(50, {a = true})
      tree:Insert(30, {b = true})
      tree:Insert(70, {c = true})
      tree:RemoveData(50, "a")
      assert.is_nil(tree:ExactMatch(50))
      assert.is_not_nil(tree:ExactMatch(30))
      assert.is_not_nil(tree:ExactMatch(70))
      local n30 = tree:ExactMatch(30)
      assert.is_nil(tree:FindParent(n30))
      assert.are.equal(30, n30.min)
      assert.are.equal(70, n30.max)
    end)

    it("removing a non-leaf with two children (inorder predecessor replacement)", function()
      tree:Insert(50, {a = true})
      tree:Insert(30, {b = true})
      tree:Insert(70, {c = true})
      tree:Insert(20, {d = true})
      tree:Insert(40, {e = true})
      tree:Insert(35, {f = true})
      local root = tree:ExactMatch(50)
      assert.are.equal(20, root.min)
      assert.are.equal(70, root.max)
      tree:RemoveData(30, "b")
      assert.is_nil(tree:ExactMatch(30))
      assert.is_not_nil(tree:ExactMatch(20))
      assert.is_not_nil(tree:ExactMatch(40))
      assert.is_not_nil(tree:ExactMatch(35))
      local newRoot = tree:ExactMatch(50)
      assert.is_not_nil(newRoot)
      assert.are.equal(20, newRoot.min)
      assert.are.equal(70, newRoot.max)
    end)

    it("removing the only node sets root to nil", function()
      tree:Insert(10, {a = true})
      tree:RemoveData(10, "a")
      assert.is_nil(tree:ExactMatch(10))
      tree:Insert(20, {b = true})
      local node = tree:ExactMatch(20)
      assert.is_not_nil(node)
      assert.are.equal(20, node.min)
      assert.are.equal(20, node.max)
    end)

    it("removing all nodes one by one maintains min/max throughout", function()
      tree:Insert(50, {a = true})
      tree:Insert(30, {b = true})
      tree:Insert(70, {c = true})
      tree:Insert(20, {d = true})
      tree:Insert(40, {e = true})
      tree:Insert(60, {f = true})
      tree:Insert(80, {g = true})

      tree:RemoveData(20, "d")
      local root = tree:ExactMatch(50)
      assert.are.equal(30, root.min)

      tree:RemoveData(80, "g")
      root = tree:ExactMatch(50)
      assert.are.equal(30, root.min)
      assert.are.equal(70, root.max)

      tree:RemoveData(50, "a")
      assert.is_nil(tree:ExactMatch(50))
      assert.is_not_nil(tree:ExactMatch(30))
      assert.is_not_nil(tree:ExactMatch(70))
    end)
  end)

  -- ─── ExactMatch ─────────────────────────────────────────────────────────────

  describe("ExactMatch", function()

    it("finds an existing value", function()
      tree:Insert(42, {x = true})
      local node = tree:ExactMatch(42)
      assert.is_not_nil(node)
      assert.are.equal(42, node.value)
    end)

    it("returns nil for a missing value", function()
      tree:Insert(10, {a = true})
      assert.is_nil(tree:ExactMatch(99))
    end)

    it("returns nil on an empty tree", function()
      assert.is_nil(tree:ExactMatch(1))
    end)

    it("finds values in the left subtree", function()
      tree:Insert(10, {a = true})
      tree:Insert(5, {b = true})
      tree:Insert(3, {c = true})
      local node = tree:ExactMatch(3)
      assert.is_not_nil(node)
      assert.are.equal(3, node.value)
    end)

    it("finds values in the right subtree", function()
      tree:Insert(10, {a = true})
      tree:Insert(15, {b = true})
      tree:Insert(20, {c = true})
      local node = tree:ExactMatch(20)
      assert.is_not_nil(node)
      assert.are.equal(20, node.value)
    end)
  end)

  -- ─── LessThan ───────────────────────────────────────────────────────────────

  describe("LessThan", function()

    it("returns nodes with values strictly less than the search value", function()
      tree:Insert(5, {a = true})
      tree:Insert(10, {b = true})
      tree:Insert(15, {c = true})
      local result = nodeValues(tree:LessThan(10))
      assert.same({5}, result)
    end)

    it("returns empty when no values are less", function()
      tree:Insert(10, {a = true})
      tree:Insert(20, {b = true})
      local result = tree:LessThan(5)
      assert.same({}, result)
    end)

    it("returns all nodes when search value is larger than all", function()
      tree:Insert(1, {a = true})
      tree:Insert(2, {b = true})
      tree:Insert(3, {c = true})
      local result = nodeValues(tree:LessThan(100))
      assert.same({1, 2, 3}, result)
    end)

    it("returns empty on an empty tree", function()
      assert.same({}, tree:LessThan(10))
    end)

    it("excludes nodes equal to the search value", function()
      tree:Insert(10, {a = true})
      tree:Insert(20, {b = true})
      tree:Insert(30, {c = true})
      local result = nodeValues(tree:LessThan(10))
      assert.same({}, result)
    end)

    it("handles a larger tree with gaps", function()
      tree:Insert(50, {a = true})
      tree:Insert(30, {b = true})
      tree:Insert(70, {c = true})
      tree:Insert(20, {d = true})
      tree:Insert(40, {e = true})
      tree:Insert(60, {f = true})
      tree:Insert(80, {g = true})
      local result = nodeValues(tree:LessThan(45))
      assert.same({20, 30, 40}, result)
    end)

    it("prunes right subtree when entire left qualifies", function()
      tree:Insert(50, {a = true})
      tree:Insert(20, {b = true})
      tree:Insert(10, {c = true})
      tree:Insert(30, {d = true})
      tree:Insert(80, {e = true})
      tree:Insert(90, {f = true})
      local result = nodeValues(tree:LessThan(40))
      assert.same({10, 20, 30}, result)
    end)

    it("handles query between two interior nodes", function()
      tree:Insert(10, {a = true})
      tree:Insert(30, {b = true})
      tree:Insert(20, {c = true})
      tree:Insert(40, {d = true})
      tree:Insert(50, {e = true})
      local result = nodeValues(tree:LessThan(35))
      assert.same({10, 20, 30}, result)
    end)
  end)

  -- ─── LessThanEqual ──────────────────────────────────────────────────────────

  describe("LessThanEqual", function()

    it("includes the exact match value", function()
      tree:Insert(5, {a = true})
      tree:Insert(10, {b = true})
      tree:Insert(15, {c = true})
      local result = nodeValues(tree:LessThanEqual(10))
      assert.same({5, 10}, result)
    end)

    it("returns empty when no values are less or equal", function()
      tree:Insert(10, {a = true})
      local result = tree:LessThanEqual(5)
      assert.same({}, result)
    end)

    it("returns empty on an empty tree", function()
      assert.same({}, tree:LessThanEqual(10))
    end)

    it("handles a larger tree with gaps", function()
      tree:Insert(50, {a = true})
      tree:Insert(30, {b = true})
      tree:Insert(70, {c = true})
      tree:Insert(20, {d = true})
      tree:Insert(40, {e = true})
      tree:Insert(60, {f = true})
      tree:Insert(80, {g = true})
      local result = nodeValues(tree:LessThanEqual(40))
      assert.same({20, 30, 40}, result)
    end)

    it("includes boundary node when query equals a tree value", function()
      tree:Insert(10, {a = true})
      tree:Insert(20, {b = true})
      tree:Insert(30, {c = true})
      local result = nodeValues(tree:LessThanEqual(20))
      assert.same({10, 20}, result)
    end)
  end)

  -- ─── GreaterThan ────────────────────────────────────────────────────────────

  describe("GreaterThan", function()

    it("returns nodes with values strictly greater than the search value", function()
      tree:Insert(5, {a = true})
      tree:Insert(10, {b = true})
      tree:Insert(15, {c = true})
      local result = nodeValues(tree:GreaterThan(10))
      assert.same({15}, result)
    end)

    it("returns empty when no values are greater", function()
      tree:Insert(10, {a = true})
      local result = tree:GreaterThan(20)
      assert.same({}, result)
    end)

    it("returns all nodes when search value is smaller than all", function()
      tree:Insert(10, {a = true})
      tree:Insert(20, {b = true})
      tree:Insert(30, {c = true})
      local result = nodeValues(tree:GreaterThan(1))
      assert.same({10, 20, 30}, result)
    end)

    it("returns empty on an empty tree", function()
      assert.same({}, tree:GreaterThan(10))
    end)

    it("excludes nodes equal to the search value", function()
      tree:Insert(10, {a = true})
      tree:Insert(20, {b = true})
      local result = nodeValues(tree:GreaterThan(10))
      assert.same({20}, result)
    end)

    it("handles a larger tree with gaps", function()
      tree:Insert(50, {a = true})
      tree:Insert(30, {b = true})
      tree:Insert(70, {c = true})
      tree:Insert(20, {d = true})
      tree:Insert(40, {e = true})
      tree:Insert(60, {f = true})
      tree:Insert(80, {g = true})
      local result = nodeValues(tree:GreaterThan(55))
      assert.same({60, 70, 80}, result)
    end)

    it("prunes left subtree when entire right qualifies", function()
      tree:Insert(50, {a = true})
      tree:Insert(30, {b = true})
      tree:Insert(80, {c = true})
      tree:Insert(70, {d = true})
      tree:Insert(90, {e = true})
      local result = nodeValues(tree:GreaterThan(60))
      assert.same({70, 80, 90}, result)
    end)

    it("handles query between two interior nodes", function()
      tree:Insert(10, {a = true})
      tree:Insert(30, {b = true})
      tree:Insert(20, {c = true})
      tree:Insert(40, {d = true})
      tree:Insert(50, {e = true})
      local result = nodeValues(tree:GreaterThan(25))
      assert.same({30, 40, 50}, result)
    end)
  end)

  -- ─── GreaterThanEqual ───────────────────────────────────────────────────────

  describe("GreaterThanEqual", function()

    it("includes the exact match value", function()
      tree:Insert(5, {a = true})
      tree:Insert(10, {b = true})
      tree:Insert(15, {c = true})
      local result = nodeValues(tree:GreaterThanEqual(10))
      assert.same({10, 15}, result)
    end)

    it("returns empty when no values are greater or equal", function()
      tree:Insert(10, {a = true})
      local result = tree:GreaterThanEqual(20)
      assert.same({}, result)
    end)

    it("returns empty on an empty tree", function()
      assert.same({}, tree:GreaterThanEqual(10))
    end)

    it("handles a larger tree with gaps", function()
      tree:Insert(50, {a = true})
      tree:Insert(30, {b = true})
      tree:Insert(70, {c = true})
      tree:Insert(20, {d = true})
      tree:Insert(40, {e = true})
      tree:Insert(60, {f = true})
      tree:Insert(80, {g = true})
      local result = nodeValues(tree:GreaterThanEqual(60))
      assert.same({60, 70, 80}, result)
    end)

    it("includes boundary node when query equals a tree value", function()
      tree:Insert(10, {a = true})
      tree:Insert(20, {b = true})
      tree:Insert(30, {c = true})
      local result = nodeValues(tree:GreaterThanEqual(20))
      assert.same({20, 30}, result)
    end)
  end)

  -- ─── Combined range queries ─────────────────────────────────────────────────

  describe("range query combinations", function()

    it("LessThan and GreaterThan on the same tree are consistent", function()
      tree:Insert(10, {a = true})
      tree:Insert(20, {b = true})
      tree:Insert(30, {c = true})
      tree:Insert(40, {d = true})
      tree:Insert(50, {e = true})
      local lt = nodeValues(tree:LessThan(35))
      local gt = nodeValues(tree:GreaterThan(35))
      local combined = {}
      for _, v in ipairs(lt) do combined[v] = true end
      for _, v in ipairs(gt) do combined[v] = true end
      local combinedList = {}
      for k in pairs(combined) do table.insert(combinedList, k) end
      table.sort(combinedList)
      assert.same({10, 20, 30, 40, 50}, combinedList)
    end)

    it("finds nothing in the gap between nodes", function()
      tree:Insert(10, {a = true})
      tree:Insert(30, {b = true})
      local lt = nodeValues(tree:LessThan(25))
      local gt = nodeValues(tree:GreaterThan(25))
      assert.same({10}, lt)
      assert.same({30}, gt)
    end)
  end)

  -- ─── Data correctness across operations ─────────────────────────────────────

  describe("data correctness", function()

    it("preserves slotkey data through range queries", function()
      tree:Insert(10, {slotA = true})
      tree:Insert(20, {slotB = true})
      tree:Insert(30, {slotC = true})
      local nodes = tree:GreaterThan(15)
      local keys = nodeSlotKeys(nodes)
      assert.is_true(keys.slotB)
      assert.is_true(keys.slotC)
      assert.is_nil(keys.slotA)
    end)

    it("preserves data after insert and remove", function()
      tree:Insert(10, {slotA = true, slotB = true})
      tree:Insert(20, {slotC = true})
      tree:RemoveData(10, "slotA")
      local node = tree:ExactMatch(10)
      assert.is_nil(node.data.slotA)
      assert.is_true(node.data.slotB)
      local node20 = tree:ExactMatch(20)
      assert.is_true(node20.data.slotC)
    end)
  end)

  -- ─── RemoveData ─────────────────────────────────────────────────────────────

  describe("RemoveData", function()

    it("removes a specific data key from a node", function()
      tree:Insert(10, {a = true, b = true})
      tree:RemoveData(10, "a")
      local node = tree:ExactMatch(10)
      assert.is_not_nil(node)
      assert.is_nil(node.data.a)
      assert.is_true(node.data.b)
    end)

    it("removes the node entirely when data becomes empty", function()
      tree:Insert(10, {a = true})
      tree:RemoveData(10, "a")
      assert.is_nil(tree:ExactMatch(10))
    end)

    it("does nothing for a non-existent value", function()
      tree:Insert(10, {a = true})
      tree:RemoveData(99, "a") -- should not error
      assert.is_not_nil(tree:ExactMatch(10))
    end)

    it("removes a leaf node and preserves the rest of the tree", function()
      tree:Insert(10, {a = true})
      tree:Insert(5, {b = true})
      tree:Insert(15, {c = true})
      tree:RemoveData(5, "b")
      assert.is_nil(tree:ExactMatch(5))
      assert.is_not_nil(tree:ExactMatch(10))
      assert.is_not_nil(tree:ExactMatch(15))
    end)

    it("removes the root node when it is the only node", function()
      tree:Insert(10, {a = true})
      tree:RemoveData(10, "a")
      assert.is_nil(tree:ExactMatch(10))
      tree:Insert(20, {b = true})
      assert.is_not_nil(tree:ExactMatch(20))
    end)

    it("range query is correct after remove and reinsert", function()
      tree:Insert(10, {a = true})
      tree:Insert(20, {b = true})
      tree:Insert(30, {c = true})
      tree:RemoveData(20, "b")
      tree:Insert(25, {d = true})
      local result = nodeValues(tree:GreaterThan(15))
      assert.same({25, 30}, result)
    end)
  end)

  -- ─── NewIntervalTree factory ────────────────────────────────────────────────

  describe("NewIntervalTree", function()

    it("creates independent tree instances", function()
      local tree2 = Trees.NewIntervalTree()
      tree:Insert(10, {a = true})
      tree2:Insert(20, {b = true})
      assert.is_nil(tree:ExactMatch(20))
      assert.is_nil(tree2:ExactMatch(10))
    end)
  end)
end)
