name: Add bugs to bugs project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/Cidan/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: bug, triage
          label-operator: OR